# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: BuildProject
  value: 'Generic.ViewModels/Generic.ViewModels.csproj'
- name: TestProject
  value: 'Generic.ViewModels.Tests/Generic.ViewModels.Tests.csproj'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(BuildProject)
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: 'Generic.ViewModels.Tests/Generic.ViewModels.Tests.csproj'
#    testRunTitle: 'test generic.viewmodels'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: $(BuildProject)
    versioningScheme: 'byBuildNumber'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'