# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  Major: '0'
  Minor: '3'
  Revision: $(Build.BuildNumber)
  BuildProject: 'Generic.ViewModels/Generic.ViewModels.csproj'
  TestProject: 'Generic.ViewModels.Tests/Generic.ViewModels.Tests.csproj'
  NuGetFeed: 'https://cninnovation.pkgs.visualstudio.com/GenericViewModelsFeed/_packaging/GenericViewModels/nuget/v3/index.json'
  
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'building revision $(Revision)' # echo

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(BuildProject)
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: 'Generic.ViewModels.Tests/Generic.ViewModels.Tests.csproj'
#    testRunTitle: 'test generic.viewmodels'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: $(BuildProject)
#    versioningScheme: 'byBuildNumber'
# '(BuildDefinitionName)_(Year:yyyy).(Month).(Month).(DayOfMonth)$(Rev:.r)'.

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd9420201-74ff-4ca9-ba65-6d989dea9334/7407cb8a-b221-4f8d-8a8f-dcfcbbf7355b'

